#!/bin/bash

. ./cavars

declare -a san
san=( "$@" )

# first name is the "name" of the cert
# it will end up in the subject field as well as the subjectAltNames
MYCERT=$1
# wildcard cert can't be the only cert #FIXME:will try to fix later
if [[ $(echo $MYCERT|cut -d. -f1) == '*' ]]
then
    echo "Certificate filenames cannot be wildcards."
    echo "Specify a single fully qualified domain name first."
    exit 1
fi

# add shortnames
for n in "$@"
do
    if [[ $(echo $n|cut -d. -f1) != '*' ]]
    then
        san+=($(echo $n|cut -d. -f1))
    fi
done

echo "Certificate subject and alternate names:"
for n in "${san[@]}"
do
    echo $n
done
echo " "

# create cert request (unless there already *is* a request!)
if [ ! -f "$MYCERT.csr.pem" ]
then
    echo "Generating certificate request for $MYCERT..."
    openssl req -new -nodes -out $MYCERT.csr.pem -newkey rsa:4096 -keyout $MYCERT.key.pem -subj "/CN=$MYCERT/O=$O/L=$L/ST=$ST/C=$C"
else
    echo "ERROR: certificate for $MYCERT already exists."
    exit 1
fi

# write an ext file for the request
cat > $MYCERT.v3.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
EOF

sancnt=${#san[*]}
for ((i=0; i<$sancnt; i++))
do
    cat >> $MYCERT.v3.ext << EOF
DNS.${i} = ${san[$i]}
EOF
done

# sign the cert w/the CA cert using the options in the ext file
echo "Signing certificate request for $MYCERT..."
openssl x509 -req -in $MYCERT.csr.pem -CA $CANAME.cert.pem -CAkey $CANAME.key.pem -CAcreateserial -out $MYCERT.cert.pem -days 730 -sha256 -extfile $MYCERT.v3.ext 

if [ $? -eq 0 ]
then
    # show our work by displaying the new cert 's info
    echo "Certificate generation for $MYCERT successful."
    echo "Certificate info:"
    openssl x509 -text -in $MYCERT.cert.pem
else
    # didn't work!
    echo "ERROR signing certificate for $MYCERT."
    exit $?
fi

